version: "3.8"

services:
  server:
    build:
      context: .
      dockerfile: ./server/Dockerfile
    ports:
      - "3030:3030"

  client:
    build:
      context: .
      dockerfile: ./client/Dockerfile
    depends_on:
      - server

  worker:
    build:
      context: .
      dockerfile: ./worker/Dockerfile
    depends_on:
      - server